AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LatestAmiId:
    Description: Region specific image from the Parameter Store
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    Default: t3.nano
  # WAFR SEC 05: Added parameter for trusted IP ranges
  TrustedCIDR:
    Description: Trusted CIDR block for SSH access (replace 0.0.0.0/0)
    Type: String
    Default: '10.0.0.0/8'
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
Resources:
  myLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
  ASGwithLaunchTemplate:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: 'wafr-test-compliant-asg'
      LaunchTemplate:
        LaunchTemplateId: !Ref myLaunchTemplate
        Version: !GetAtt myLaunchTemplate.LatestVersionNumber
      MaxSize: '0'
      MinSize: '0'
      VPCZoneIdentifier:
        - !ImportValue SubnetAID
        - !ImportValue SubnetBID
  ASGwithLaunchConfig:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      VPCZoneIdentifier:
        - !ImportValue SubnetAID
        - !ImportValue SubnetBID   
      LaunchConfigurationName: !Ref MyLaunchConfiguration
      MinSize: "0"
      MaxSize: "0"
      DesiredCapacity: "0"

  MyLaunchConfiguration:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      SecurityGroups: 
        - !Ref MySecurityGroup

  # WAFR SEC 05: Restricted Security Group - replaces lines 58-66
  # AWS Documentation: https://docs.aws.amazon.com/vpc/latest/userguide/security-group-rules.html
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "WAFR Compliant - Restricted SSH and HTTP access"
      VpcId: !ImportValue VPCID
      SecurityGroupIngress: 
        # SSH access restricted to trusted CIDR (not 0.0.0.0/0)
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref TrustedCIDR
          Description: "SSH access from trusted network only"
        # HTTP access from ALB security group (not 0.0.0.0/0)
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: "HTTP access from ALB only"
      # WAFR SEC 05: Explicit egress rules for least privilege
      SecurityGroupEgress:
        # Only allow HTTPS outbound for package updates
        - IpProtocol: "tcp"
          FromPort: "443"
          ToPort: "443"
          CidrIp: "0.0.0.0/0"
          Description: "HTTPS for package updates"
        # DNS resolution
        - IpProtocol: "udp"
          FromPort: "53"
          ToPort: "53"
          CidrIp: "0.0.0.0/0"
          Description: "DNS resolution"
      Tags:
        - Key: "WAFR-Compliance"
          Value: "SEC-05-Network-Protection"

  # WAFR SEC 05: Added ALB Security Group for proper traffic flow
  ALBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "WAFR Compliant ALB Security Group"
      VpcId: !ImportValue VPCID
      SecurityGroupIngress: 
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"
          Description: "HTTP from internet to ALB"
        - IpProtocol: "tcp"
          FromPort: "443"
          ToPort: "443"
          CidrIp: "0.0.0.0/0"
          Description: "HTTPS from internet to ALB"
      Tags:
        - Key: "WAFR-Compliance"
          Value: "SEC-05-ALB-Security"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      # WAFR SEC 03: Least privilege IAM policies (not wildcard)
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ASGReadOnlyPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - autoscaling:DescribeAutoScalingGroups
                Resource: "*"
                Condition:
                  StringEquals:
                    "aws:RequestedRegion": !Ref "AWS::Region"

  myASGFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt 'LambdaExecutionRole.Arn'
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          def handler(event, context):
              client = boto3.client('autoscaling')
              response = client.describe_auto_scaling_groups(
                  AutoScalingGroupNames=[
                    'wafr-test-compliant-asg'
                  ]
              )
              responseData = {'AutoScalingGroupARN': response['AutoScalingGroups'][0]['AutoScalingGroupARN']}
              cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
      Runtime: python3.11
      Timeout: '30'
      # WAFR REL 08: Function monitoring with CloudWatch logs
      Environment:
        Variables:
          LOG_LEVEL: INFO
  
  MyASGFunctionCall:
    Type: Custom::MyASGFunction
    Properties:
      ServiceToken: !GetAtt myASGFunction.Arn

Outputs:
  ASGwithLaunchTemplateARN:
    Description: Auto Scaling Group with launch template ARN.
    Value: !GetAtt 'MyASGFunctionCall.AutoScalingGroupARN'
  ASGwithLaunchConfigID:
    Description: Auto Scaling Group with launch config ID
    Value: !Ref ASGwithLaunchConfig
  AccountIdRegion:
    Description: AccountIdRegion
    Value: !Join ["", [!Ref AWS::AccountId, "/", !Ref AWS::Region]]
  # WAFR SEC 05: Output security group IDs for reference
  MySecurityGroupId:
    Description: Compliant Security Group ID for EC2 instances
    Value: !Ref MySecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-CompliantSG"
  ALBSecurityGroupId:
    Description: ALB Security Group ID
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-ALBSG"