AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LatestAmiId:
    Description: Region specific image from the Parameter Store
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    Default: t3.nano
  # WAFR REMEDIATION: Added parameter for restricted SSH access
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    Default: "10.0.0.0/8"
    AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$
    ConstraintDescription: Must be a valid IP CIDR range
Resources:
  myLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        # WAFR REMEDIATION (REL-8): Added security group to launch template for better security
        SecurityGroupIds:
          - !Ref MySecurityGroup
  ASGwithLaunchTemplate:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: 'wafr-compliant-asg'
      LaunchTemplate:
        LaunchTemplateId: !Ref myLaunchTemplate
        Version: !GetAtt myLaunchTemplate.LatestVersionNumber
      # WAFR REMEDIATION (REL-8): Set proper scaling parameters for fault tolerance
      # AWS Well-Architected Reliability Pillar - Question REL-8: How do you implement change?
      # Reference: https://docs.aws.amazon.com/autoscaling/ec2/userguide/auto-scaling-benefits.html
      MaxSize: '3'
      MinSize: '1'
      DesiredCapacity: '2'
      VPCZoneIdentifier:
        - !ImportValue SubnetAID
        - !ImportValue SubnetBID
      # WAFR REMEDIATION (REL-8): Added health check configuration
      HealthCheckGracePeriod: 300
      HealthCheckType: 'ELB'
  ASGwithLaunchConfig:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      VPCZoneIdentifier:
        - !ImportValue SubnetAID
        - !ImportValue SubnetBID   
      LaunchConfigurationName: !Ref MyLaunchConfiguration
      # WAFR REMEDIATION (REL-8): Set proper scaling parameters
      MinSize: "1"
      MaxSize: "3"
      DesiredCapacity: "2"
      # WAFR REMEDIATION (REL-8): Added health check configuration
      HealthCheckGracePeriod: 300
      HealthCheckType: 'EC2'

  MyLaunchConfiguration:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      SecurityGroups: 
        - !Ref MySecurityGroup

  # WAFR REMEDIATION (SEC-3): Implemented restricted security group rules
  # AWS Well-Architected Security Pillar - Question SEC-3: How do you control traffic at all layers?
  # Reference: https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#SecurityGroupRules
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Restricted SSH and HTTP access with WAFR compliance"
      VpcId: !ImportValue VPCID
      SecurityGroupIngress: 
        # WAFR FIX: Restricted SSH access to private networks only (was 0.0.0.0/0)
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref SSHLocation
          Description: "SSH access from private networks only"
        # WAFR FIX: HTTP access restricted to ALB security group (implement proper load balancer)
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: "HTTP access from Application Load Balancer only"
      # WAFR REMEDIATION: Added explicit egress rules for better security
      SecurityGroupEgress:
        - IpProtocol: "tcp"
          FromPort: "443"
          ToPort: "443"
          CidrIp: "0.0.0.0/0"
          Description: "HTTPS outbound for updates and patches"
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"
          Description: "HTTP outbound for package management"
      Tags:
        - Key: "WAFRCompliant"
          Value: "true"
        - Key: "SecurityReview"
          Value: "2026-01-19"

  # WAFR REMEDIATION (SEC-3): Added ALB Security Group for proper traffic flow
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for Application Load Balancer - WAFR compliant"
      VpcId: !ImportValue VPCID
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"
          Description: "HTTP access from internet via ALB"
        - IpProtocol: "tcp"
          FromPort: "443"
          ToPort: "443"
          CidrIp: "0.0.0.0/0"
          Description: "HTTPS access from internet via ALB"
      Tags:
        - Key: "WAFRCompliant"
          Value: "true"

  # WAFR REMEDIATION (SEC-2): Implemented least privilege IAM role
  # AWS Well-Architected Security Pillar - Question SEC-2: How do you control access to people and systems?
  # Reference: https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#grant-least-privilege
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      # WAFR FIX: Replaced overly broad permissions with specific, minimal required permissions
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: "ASGDescribeOnlyPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - autoscaling:DescribeAutoScalingGroups
                Resource: 
                  - !Sub "arn:aws:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*:autoScalingGroupName/wafr-compliant-asg"
              # WAFR REMEDIATION: Added CloudWatch Logs permissions for monitoring
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
      Tags:
        - Key: "WAFRCompliant"
          Value: "true"

  myASGFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt 'LambdaExecutionRole.Arn'
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import logging
          
          # WAFR REMEDIATION (OPS-7): Added proper logging for operational excellence
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          
          def handler(event, context):
              try:
                  logger.info(f"Processing event: {event['RequestType']}")
                  client = boto3.client('autoscaling')
                  response = client.describe_auto_scaling_groups(
                      AutoScalingGroupNames=[
                        'wafr-compliant-asg'
                      ]
                  )
                  
                  if not response['AutoScalingGroups']:
                      raise Exception("Auto Scaling Group not found")
                  
                  responseData = {'AutoScalingGroupARN': response['AutoScalingGroups'][0]['AutoScalingGroupARN']}
                  logger.info(f"Successfully retrieved ASG ARN: {responseData['AutoScalingGroupARN']}")
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
              except Exception as e:
                  logger.error(f"Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {}, str(e))
      Runtime: python3.11
      # WAFR REMEDIATION (REL-4): Increased timeout for reliability
      Timeout: '60'
      # WAFR REMEDIATION (OPS-7): Added environment variables for configuration
      Environment:
        Variables:
          LOG_LEVEL: 'INFO'
      # WAFR REMEDIATION (PERF-2): Added memory configuration for performance
      MemorySize: 128
      Tags:
        - Key: "WAFRCompliant"
          Value: "true"
          
  MyASGFunctionCall:
    Type: Custom::MyASGFunction
    Properties:
      ServiceToken: !GetAtt myASGFunction.Arn

Outputs:
  ASGwithLaunchTemplateARN:
    Description: Auto Scaling Group with launch template ARN.
    Value: !GetAtt 'MyASGFunctionCall.AutoScalingGroupARN'
  ASGwithLaunchConfigID:
    Description: Auto Scaling Group with launch config ID
    Value: !Ref ASGwithLaunchConfig
  AccountIdRegion:
    Description: AccountIdRegion
    Value: !Join ["", [!Ref AWS::AccountId, "/", !Ref AWS::Region]]
  # WAFR REMEDIATION: Added security-related outputs for monitoring
  SecurityGroupId:
    Description: ID of the WAFR-compliant security group
    Value: !Ref MySecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroup"
  ALBSecurityGroupId:
    Description: ID of the ALB security group
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-ALBSecurityGroup"