AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LatestAmiId:
    Description: Region specific image from the Parameter Store
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    Default: t3.nano
  # WAFR SECURITY REMEDIATION: Add parameter for allowed CIDR blocks
  AllowedCIDR:
    Description: CIDR block allowed for SSH access (replace 0.0.0.0/0 with your IP)
    Type: String
    Default: "10.0.0.0/8"
    ConstraintDescription: Must be a valid CIDR block
Resources:
  myLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        # WAFR SECURITY REMEDIATION: Add security group to launch template
        SecurityGroupIds:
          - !Ref MySecurityGroup
  ASGwithLaunchTemplate:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: 'wafr-test-compliant-asg'
      LaunchTemplate:
        LaunchTemplateId: !Ref myLaunchTemplate
        Version: !GetAtt myLaunchTemplate.LatestVersionNumber
      MaxSize: '3'  # WAFR RELIABILITY: Increased for scaling
      MinSize: '1'   # WAFR RELIABILITY: Minimum instances for availability
      DesiredCapacity: '2'  # WAFR RELIABILITY: Desired capacity for redundancy
      # WAFR RELIABILITY REMEDIATION: Multi-AZ deployment
      VPCZoneIdentifier:
        - !ImportValue SubnetAID
        - !ImportValue SubnetBID
        - !ImportValue SubnetCID  # Added third AZ for better availability
      # WAFR RELIABILITY: Add health check configuration
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      # WAFR OPERATIONAL EXCELLENCE: Add tags for better resource management
      Tags:
        - Key: Environment
          Value: Production
          PropagateAtLaunch: true
        - Key: WAFR-Compliant
          Value: 'true'
          PropagateAtLaunch: true
  ASGwithLaunchConfig:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      VPCZoneIdentifier:
        - !ImportValue SubnetAID
        - !ImportValue SubnetBID   
      LaunchConfigurationName: !Ref MyLaunchConfiguration
      MinSize: "1"  # WAFR RELIABILITY: Minimum for availability
      MaxSize: "3"  # WAFR RELIABILITY: Allow scaling
      DesiredCapacity: "2"  # WAFR RELIABILITY: Desired capacity

  MyLaunchConfiguration:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      SecurityGroups: 
        - !Ref MySecurityGroup
      # WAFR SECURITY REMEDIATION: Add IAM instance profile
      IamInstanceProfile: !Ref EC2InstanceProfile

  # WAFR SECURITY REMEDIATION: Secure Security Group
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "WAFR Compliant - Restricted SSH and HTTP access"
      VpcId: !ImportValue VPCID
      SecurityGroupIngress: 
        # WAFR SECURITY REMEDIATION: Restricted SSH access from specific CIDR only
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref AllowedCIDR  # Use parameter instead of 0.0.0.0/0
          Description: "SSH access from trusted network only"
        # WAFR SECURITY REMEDIATION: HTTP access through ALB security group only
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: "HTTP access from ALB only"
      # WAFR SECURITY: Explicit egress rules
      SecurityGroupEgress:
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"
          Description: "HTTP outbound for updates"
        - IpProtocol: "tcp"
          FromPort: "443"
          ToPort: "443"
          CidrIp: "0.0.0.0/0"
          Description: "HTTPS outbound for updates"
      Tags:
        - Key: Name
          Value: WAFR-Compliant-SG

  # WAFR SECURITY REMEDIATION: Add ALB Security Group
  ALBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group for Application Load Balancer"
      VpcId: !ImportValue VPCID
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"
          Description: "HTTP from internet via ALB"
        - IpProtocol: "tcp"
          FromPort: "443"
          ToPort: "443"
          CidrIp: "0.0.0.0/0"
          Description: "HTTPS from internet via ALB"
      Tags:
        - Key: Name
          Value: ALB-Security-Group

  # WAFR SECURITY REMEDIATION: Secure IAM Role with minimal permissions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-LambdaExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      # WAFR SECURITY REMEDIATION: Specific permissions instead of wildcard
      Policies:
        - PolicyName: SpecificAutoScalingAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - autoscaling:DescribeAutoScalingGroups
                Resource: 
                  - !Sub "arn:aws:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*:autoScalingGroupName/wafr-test-compliant-asg"

  # WAFR SECURITY REMEDIATION: EC2 Instance Profile with minimal permissions
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore  # For Systems Manager
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy   # For monitoring

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  myASGFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-ASGFunction"
      Handler: index.handler
      Role: !GetAtt 'LambdaExecutionRole.Arn'
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import logging
          
          # WAFR OPERATIONAL EXCELLENCE: Proper logging
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          
          def handler(event, context):
              try:
                  client = boto3.client('autoscaling')
                  response = client.describe_auto_scaling_groups(
                      AutoScalingGroupNames=[
                        'wafr-test-compliant-asg'
                      ]
                  )
                  if response['AutoScalingGroups']:
                      responseData = {'AutoScalingGroupARN': response['AutoScalingGroups'][0]['AutoScalingGroupARN']}
                      logger.info(f"Successfully retrieved ASG ARN: {responseData['AutoScalingGroupARN']}")
                  else:
                      responseData = {'AutoScalingGroupARN': 'ASG not found'}
                      logger.warning("ASG not found")
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
              except Exception as e:
                  logger.error(f"Error retrieving ASG info: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Error': str(e)})
      Runtime: python3.11
      Timeout: '30'
      # WAFR OPERATIONAL EXCELLENCE: Add environment variables for configuration
      Environment:
        Variables:
          LOG_LEVEL: INFO
      # WAFR RELIABILITY: Add dead letter queue for failed invocations
      DeadLetterConfig:
        TargetArn: !GetAtt DeadLetterQueue.Arn

  # WAFR RELIABILITY REMEDIATION: Add DLQ for Lambda failure handling
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-dlq"
      MessageRetentionPeriod: 1209600  # 14 days

  MyASGFunctionCall:
    Type: Custom::MyASGFunction
    Properties:
      ServiceToken: !GetAtt myASGFunction.Arn

Outputs:
  ASGwithLaunchTemplateARN:
    Description: Auto Scaling Group with launch template ARN.
    Value: !GetAtt 'MyASGFunctionCall.AutoScalingGroupARN'
  ASGwithLaunchConfigID:
    Description: Auto Scaling Group with launch config ID
    Value: !Ref ASGwithLaunchConfig
  AccountIdRegion:
    Description: AccountIdRegion
    Value: !Join ["", [!Ref AWS::AccountId, "/", !Ref AWS::Region]]
  # WAFR OPERATIONAL EXCELLENCE: Add security group outputs for reference
  MySecurityGroupId:
    Description: ID of the WAFR compliant security group
    Value: !Ref MySecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SecureSecurityGroup"
  ALBSecurityGroupId:
    Description: ID of the ALB security group
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-ALBSecurityGroup"