AWSTemplateFormatVersion: '2010-09-09'
# WAFR Remediation: Fixed critical security and reliability issues
# Fixes applied for SEC-2, SEC-3, OPS-4, REL-1 WAFR questions
Parameters:
  LatestAmiId:
    Description: Region specific image from the Parameter Store
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    Default: t3.nano
  AllowedCIDR:
    Description: CIDR block allowed for SSH access (WAFR SEC-2 fix)
    Type: String
    Default: "10.0.0.0/8"  # Replace with your specific CIDR
    
Resources:
  # WAFR SEC-8: Add KMS key for encryption
  ASGKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "KMS Key for ASG encryption (WAFR SEC-8)"
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow use of the key for Auto Scaling
            Effect: Allow
            Principal:
              Service: autoscaling.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Resource: '*'

  ASGKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/asg-encryption-key
      TargetKeyId: !Ref ASGKMSKey

  myLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        # WAFR SEC-8: Enable EBS encryption
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeType: gp3
              VolumeSize: 20
              Encrypted: true
              KmsKeyId: !Ref ASGKMSKey
        # WAFR OPS-4: Enable detailed monitoring
        Monitoring:
          Enabled: true
        SecurityGroupIds:
          - !Ref MySecurityGroup
        # WAFR SEC-3: Use IAM instance profile with least privilege
        IamInstanceProfile:
          Arn: !GetAtt EC2InstanceProfile.Arn
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            # WAFR OPS-4: Install CloudWatch agent
            yum install -y amazon-cloudwatch-agent
            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c ssm:AmazonCloudWatch-linux

  ASGwithLaunchTemplate:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: 'wafr-compliant-asg'
      LaunchTemplate:
        LaunchTemplateId: !Ref myLaunchTemplate
        Version: !GetAtt myLaunchTemplate.LatestVersionNumber
      # WAFR REL-1: Multi-AZ deployment for high availability
      MaxSize: '6'
      MinSize: '2'
      DesiredCapacity: '2'
      VPCZoneIdentifier:
        - !ImportValue SubnetAID
        - !ImportValue SubnetBID
        - !ImportValue SubnetCID  # Added third AZ for better resilience
      # WAFR REL-1: Enable health checks
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      # WAFR OPS-4: Add tags for monitoring
      Tags:
        - Key: Name
          Value: WAFR-Compliant-ASG
          PropagateAtLaunch: true
        - Key: Environment
          Value: Production
          PropagateAtLaunch: true
        - Key: WAFR-Compliant
          Value: true
          PropagateAtLaunch: true

  ASGwithLaunchConfig:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      VPCZoneIdentifier:
        - !ImportValue SubnetAID
        - !ImportValue SubnetBID
        - !ImportValue SubnetCID   
      LaunchConfigurationName: !Ref MyLaunchConfiguration
      MinSize: "2"
      MaxSize: "6"
      DesiredCapacity: "2"
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300

  MyLaunchConfiguration:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      SecurityGroups: 
        - !Ref MySecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      # WAFR SEC-8: Enable EBS encryption
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
            Encrypted: true
            KmsKeyId: !Ref ASGKMSKey
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y amazon-cloudwatch-agent

  # WAFR SEC-2: Restricted Security Group (no more 0.0.0.0/0)
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Restricted access following WAFR SEC-2 guidelines"
      VpcId: !ImportValue VPCID
      SecurityGroupIngress: 
        # SSH access restricted to specific CIDR (WAFR SEC-2)
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref AllowedCIDR
          Description: "SSH access from allowed CIDR only"
        # HTTP access restricted to private networks
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "10.0.0.0/8"
          Description: "HTTP access from private networks only"
      SecurityGroupEgress:
        # WAFR SEC-2: Restrict outbound traffic to HTTPS only
        - IpProtocol: "tcp"
          FromPort: "443"
          ToPort: "443"
          CidrIp: "0.0.0.0/0"
          Description: "HTTPS outbound for updates and API calls"
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"
          Description: "HTTP outbound for package downloads"

  # WAFR SEC-3: Least privilege IAM role
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-EC2-Role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: MinimalEC2Permissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - ec2:DescribeVolumes
                  - ec2:DescribeTags
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                Resource: '*'
                # WAFR SEC-3: Restrict to specific resources where possible
                Condition:
                  StringEquals:
                    'aws:RequestedRegion': !Ref 'AWS::Region'

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  # WAFR SEC-3: Restricted Lambda execution role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-Lambda-Role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DescribeAutoScalingOnly
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - autoscaling:DescribeAutoScalingGroups
                Resource: !Sub "arn:aws:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*:autoScalingGroupName/wafr-compliant-asg"

  myASGFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt 'LambdaExecutionRole.Arn'
      # WAFR SEC-8: Enable encryption for Lambda environment
      KmsKeyArn: !GetAtt ASGKMSKey.Arn
      # WAFR REL-1: Set appropriate timeout
      Timeout: 30
      # WAFR REL-1: Configure dead letter queue
      DeadLetterConfig:
        TargetArn: !Ref ASGDLQueue
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import logging
          
          # WAFR OPS-4: Proper logging configuration
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          
          def handler(event, context):
              try:
                  client = boto3.client('autoscaling')
                  response = client.describe_auto_scaling_groups(
                      AutoScalingGroupNames=['wafr-compliant-asg']
                  )
                  
                  if response['AutoScalingGroups']:
                      responseData = {'AutoScalingGroupARN': response['AutoScalingGroups'][0]['AutoScalingGroupARN']}
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
                  else:
                      logger.error("Auto Scaling Group not found")
                      cfnresponse.send(event, context, cfnresponse.FAILED, {})
              except Exception as e:
                  logger.error(f"Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {})
      Runtime: python3.11
      Environment:
        Variables:
          LOG_LEVEL: INFO

  # WAFR REL-1: Dead Letter Queue for Lambda
  ASGDLQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-asg-dlq"
      MessageRetentionPeriod: 1209600  # 14 days
      KmsMasterKeyId: !Ref ASGKMSKey

  MyASGFunctionCall:
    Type: Custom::MyASGFunction
    Properties:
      ServiceToken: !GetAtt myASGFunction.Arn

  # WAFR OPS-4: CloudWatch Alarms for monitoring
  ASGHighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-ASG-HighCPU"
      AlarmDescription: "Alarm when ASG CPU exceeds 80%"
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref ASGwithLaunchTemplate
      AlarmActions:
        - !Ref SNSAlert

  # WAFR OPS-4: SNS topic for alerts
  SNSAlert:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-alerts"
      KmsMasterKeyId: !Ref ASGKMSKey
      DisplayName: "ASG Monitoring Alerts"

Outputs:
  ASGwithLaunchTemplateARN:
    Description: Auto Scaling Group with launch template ARN.
    Value: !GetAtt 'MyASGFunctionCall.AutoScalingGroupARN'
  ASGwithLaunchConfigID:
    Description: Auto Scaling Group with launch config ID
    Value: !Ref ASGwithLaunchConfig
  AccountIdRegion:
    Description: AccountIdRegion
    Value: !Join ["", [!Ref AWS::AccountId, "/", !Ref AWS::Region]]
  WAFRComplianceStatus:
    Description: WAFR compliance improvements applied
    Value: "SEC-2,SEC-3,SEC-8,OPS-4,REL-1 remediated"
  KMSKeyId:
    Description: KMS Key for encryption
    Value: !Ref ASGKMSKey
    Export:
      Name: !Sub "${AWS::StackName}-KMSKey"