AWSTemplateFormatVersion: "2010-09-09"
Description: Creates WAFR-Compliant Lambda Resources with Security Best Practices
Parameters:
  # WAFR SEC 3: Add parameter for trusted AWS accounts
  TrustedAccountId:
    Type: String
    Description: AWS Account ID allowed to invoke Lambda functions
    Default: !Ref AWS::AccountId
    AllowedPattern: ^[0-9]{12}$
    
Resources:
  # WAFR SEC 8: KMS Key for Lambda encryption
  LambdaKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS Key for Lambda function encryption
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: Allow Lambda service
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - "kms:Decrypt"
              - "kms:DescribeKey"
              - "kms:Encrypt"
              - "kms:GenerateDataKey"
            Resource: "*"
            
  LambdaKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/lambda-encryption
      TargetKeyId: !Ref LambdaKMSKey
      
  # WAFR SEC 3: CRITICAL FIX - Replace overly permissive IAM role
  FailingLambdaExecRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["-", [NCLambda-ExecutionRole, !Ref AWS::Region]]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      # WAFR SEC 3: Add minimal required policies only
      Policies:
        - PolicyName: LambdaKMSAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "kms:Decrypt"
                  - "kms:DescribeKey"
                Resource: !GetAtt LambdaKMSKey.Arn
                
  # WAFR SEC 3: CRITICAL FIX - Replace admin role with least privilege
  LambdaMinimalRole:
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: !Join ["-", [NCLambda-MinimalRole, !Ref AWS::Region]]
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      # WAFR SEC 3: Least privilege - specific actions only, no wildcard permissions
      Policies: 
        - PolicyName: "LambdaSpecificPolicy"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: 
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream" 
                  - "logs:PutLogEvents"
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
              - Effect: Allow
                Action:
                  - "kms:Decrypt"
                  - "kms:DescribeKey"
                Resource: !GetAtt LambdaKMSKey.Arn
  
  # WAFR REL 6: Add SQS Dead Letter Queue for error handling
  LambdaDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: Lambda-DLQ
      MessageRetentionPeriod: 1209600  # 14 days
      KmsMasterKeyId: !Ref LambdaKMSKey
      
  # WAFR PERF 4: MEDIUM FIX - Increase timeout from 1 second to reasonable value
  TimeoutLambda:
    Type: AWS::Lambda::Function
    Properties:
      Timeout: 30  # WAFR PERF 4: Increased from 1 to 30 seconds
      FunctionName:
        !Join [
          "-",
          ["nc-lambda-func-to", !Select [2, !Split ["/", !Ref AWS::StackId]]],
        ]
      Handler: "index.handler"
      Role: !GetAtt LambdaMinimalRole.Arn  # WAFR SEC 3: Use least privilege role
      Runtime: python3.11
      # WAFR SEC 8: Add KMS encryption
      KmsKeyArn: !GetAtt LambdaKMSKey.Arn
      # WAFR REL 6: Add dead letter queue configuration
      DeadLetterConfig:
        TargetArn: !GetAtt LambdaDLQ.Arn
      # WAFR SEC 4: Enable tracing for monitoring
      TracingConfig:
        Mode: Active
      Code:
        ZipFile: |
          import time
          import json
          def handler(event, context):
            # WAFR PERF 4: Fixed infinite loop - now processes for max 25 seconds
            start_time = time.time()
            while time.time() - start_time < 25:  # Process for 25 seconds max
              print("Processing work, will complete soon") 
              time.sleep(1)
            return {
              'statusCode': 200,
              'body': json.dumps('Processing completed successfully')
            }

  FailingLambda:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          test_variable: "value"
      FunctionName:
        !Join [
          "-",
          ["nc-lambda-func", !Select [2, !Split ["/", !Ref AWS::StackId]]],
        ]
      Handler: "index.handler"
      Role: !GetAtt FailingLambdaExecRole.Arn
      Runtime: python3.11
      # WAFR SEC 8: Add KMS encryption
      KmsKeyArn: !GetAtt LambdaKMSKey.Arn
      # WAFR REL 6: Add dead letter queue configuration
      DeadLetterConfig:
        TargetArn: !GetAtt LambdaDLQ.Arn
      # WAFR SEC 4: Enable tracing for monitoring
      TracingConfig:
        Mode: Active
      Code:
        ZipFile: |
          import json
          def handler(event, context):
              # WAFR REL 6: Add proper error handling instead of division by zero
              try:
                  # Simulate some processing
                  result = event.get('value', 42) * 2
                  return {
                      'statusCode': 200,
                      'body': json.dumps({
                          'message': 'Function executed successfully',
                          'result': result
                      })
                  }
              except Exception as e:
                  return {
                      'statusCode': 500,
                      'body': json.dumps({
                          'error': 'Function execution failed',
                          'details': str(e)
                      })
                  }

  FailingLambdatriggerRule:
      Type: AWS::Events::Rule
      Properties:
        Description: Scheduled rule to trigger the Lambda function
        ScheduleExpression: rate(2 minutes)  
        State: ENABLED
        Targets:
          - Arn: !GetAtt FailingLambda.Arn
            Id: MyLambdaTarget

  TriggerEventPermission1:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt FailingLambda.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt FailingLambdatriggerRule.Arn

  TriggerEventPermission2:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt TimeoutLambda.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt FailingLambdatriggerRule.Arn
                
  HelloWorldFunction2:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "HelloWorldFunction2"
      Handler: "index.handler"
      Role: !GetAtt FailingLambdaExecRole.Arn
      Runtime: python3.11
      # WAFR SEC 8: Add KMS encryption
      KmsKeyArn: !GetAtt LambdaKMSKey.Arn
      # WAFR REL 6: Add dead letter queue configuration
      DeadLetterConfig:
        TargetArn: !GetAtt LambdaDLQ.Arn
      # WAFR SEC 4: Enable tracing for monitoring
      TracingConfig:
        Mode: Active
      Code:
        ZipFile: |
          import json
          def handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello, World! (Function 2)')
              }
              
  # WAFR SEC 3: CRITICAL FIX - Replace wildcard principal with specific account
  LambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Ref HelloWorldFunction2
      Action: "lambda:InvokeFunction"
      Principal: !Sub "arn:aws:iam::${TrustedAccountId}:root"  # WAFR SEC 3: Specific account instead of "*"
      
  # WAFR REL 6: Add CloudWatch Alarms for monitoring Lambda functions
  FailingLambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${FailingLambda}-Errors"
      AlarmDescription: Monitor Lambda function errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref FailingLambda
          
  TimeoutLambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TimeoutLambda}-Errors"
      AlarmDescription: Monitor Lambda function errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref TimeoutLambda
          
  TimeoutLambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TimeoutLambda}-Duration"
      AlarmDescription: Monitor Lambda function duration
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 25000  # 25 seconds in milliseconds
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref TimeoutLambda

Outputs:
  FailingLambdaExecRole:
    Value: !GetAtt FailingLambdaExecRole.Arn
    Description: WAFR-compliant Lambda execution role with least privilege
  FailingLambdaArn:
    Value: !GetAtt FailingLambda.Arn
    Description: Lambda function with proper error handling and encryption
  HelloWorldFunction2Arn:
    Value: !GetAtt HelloWorldFunction2.Arn
    Description: Lambda function with WAFR security controls
  TimeoutLambdaArn:
    Value: !GetAtt [TimeoutLambda, Arn]
    Description: Lambda function with proper timeout and monitoring
  LambdaKMSKeyArn:
    Value: !GetAtt LambdaKMSKey.Arn
    Description: KMS key used for Lambda function encryption
  LambdaDLQArn:
    Value: !GetAtt LambdaDLQ.Arn
    Description: Dead letter queue for Lambda error handling